package com.example.risk.generator;

import com.example.risk.generator.distribution.Distribution;
import com.example.risk.model.RiskRecord;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Generates synthetic RiskRecord lists from a {@link GeneratorConfig}.
 *
 * <p>Attribute values are drawn from fixed pools ("attr0_v3", etc.) so that
 * GROUP BY produces a predictable number of groups regardless of record count.
 *
 * <p>Each record's numbers[] is generated by a randomly chosen Distribution,
 * allowing different records to follow different statistical behaviours.
 */
public class SyntheticDataGenerator {

    public List<RiskRecord> generate(GeneratorConfig config) {
        Random rng = new Random(config.getSeed());
        List<Distribution> dists = config.getDistributions();

        // Build per-attribute value pools
        List<List<String>> pools = buildPools(config.getNumAttributes(),
                                              config.getAttributeCardinality());

        List<RiskRecord> records = new ArrayList<>(config.getNumRecords());
        for (int r = 0; r < config.getNumRecords(); r++) {
            List<String> attrs = new ArrayList<>(config.getNumAttributes());
            for (List<String> pool : pools) {
                attrs.add(pool.get(rng.nextInt(pool.size())));
            }

            // Pick a distribution — different records can use different distributions
            Distribution dist = dists.get(rng.nextInt(dists.size()));
            double[] numbers  = dist.generate(config.getNumbersLength());

            records.add(new RiskRecord(config.getDatasetId(), attrs, numbers));
        }
        return records;
    }

    private static List<List<String>> buildPools(int numAttributes, int cardinality) {
        List<List<String>> pools = new ArrayList<>(numAttributes);
        for (int a = 0; a < numAttributes; a++) {
            List<String> pool = new ArrayList<>(cardinality);
            for (int v = 0; v < cardinality; v++) pool.add("a" + a + "v" + v);
            pools.add(pool);
        }
        return pools;
    }
}
